### ISSUE TITLE
操作一栏填写什么呢？ 是发送到plc的指令吗？

### ISSUE THREAD

**Issue by copyshop** [alidili/SerialPortDemo#3]
操作一栏我随便写一个，出现下面这种错误。我只是想读取线圈状态。不胜感激。3q

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000240f7d44465, pid=9228, tid=0x0000000000002cf8
#
# JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [rxtxSerial.dll+0x4465]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\MyData\heyin\Desktop\SerialPortDemo\hs_err_pid9228.log
#
# If you would like to submit a bug report, please visit:
#
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by copyshop** [comment]
第一次接触modbus，我想读取线圈状态，应该用你这个demo ，发送什么指令。谢谢。

**Comment by alidili** [comment]
操作栏里可以输入字符串（选择ASCII），或者十六进制字符串（选择Hex），对modbus不太了解，发送的指令应该有协议文档的，可以查一查

**Comment by copyshop** [comment]
我现在迷惑的是modbus指令这方面，谢谢你的解答。

**Comment by zhangyang1995** [comment]
我有同样的报错 C [rxtxSerial.dll+0x4465] 这个是怎么解决的？求教 谢谢

**Comment by Ggbr-TaoLi** [comment]
我也是报错 C [rxtxSerial.dll+0x4465] ？之前还能用的，求教

**Comment by alidili** [comment]
> 我也是报错 C [rxtxSerial.dll+0x4465] ？之前还能用的，求教

把JDK版本换成8u101版本试试
