### ISSUE TITLE
# Problematic frame: # C  [rxtxSerial.dll+0x4465]

### ISSUE THREAD

**Issue by zhangyang1995** [alidili/SerialPortDemo#4]
按照操作做了 输入信息后 点击发送数据
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000180004465, pid=14496, tid=0x0000000000004f44
#
# JRE version: Java(TM) SE Runtime Environment (8.0_261-b12) (build 1.8.0_261-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.261-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [rxtxSerial.dll+0x4465]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:

**Comment by alidili** [comment]
An error report file with more information is saved as:

这个下面有个log日志，内容贴一下
